package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "shared_ptr_pimpl",
    srcs = [
        "shared_ptr_pimpl.cc",
    ],
)

cc_binary(
    name = "weak_ptr_singleton",
    srcs = [
        "weak_ptr_singleton.cc",
    ],
)
