cc_binary(
    name = "particle_reader",
    srcs = [
        "ParticleReader.cxx",
    ],
    deps = [
        "@vtk//:vtk",
    ],
)

sh_test(
    name = "vtk_test",
    srcs = [
        "vtk_test.sh",
    ],
)
