package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "copy_ctor",
    srcs = ["copy_ctor.cc"],
)

cc_binary(
    name = "tpl_inst_main",
    srcs = ["tpl_inst_main.cc", "tpl_inst.cc", "tpl_inst.h", "name_trait.h"],
)

cc_binary(
    name = "virtual_template",
    srcs = ["virtual_template.cc"],
)

cc_binary(
    name = "forward",
    srcs = ["forward.cc"],
)

cc_binary(
    name = "recursive_template",
    srcs = ["recursive_template.cc"],
)

cc_binary(
    name = "constexpr",
    srcs = ["constexpr.cc"],
)

cc_binary(
    name = "name_trait_main",
    srcs = ["name_trait_main.cc", "name_trait.h"],
)

cc_binary(
    name = "prevent_implicit_conversion",
    srcs = ["prevent_implicit_conversion.cc", "name_trait.h", "drake_copy.h"],
)

cc_binary(
    name = "tpl_spec_return_type_main",
    srcs = ["tpl_spec_return_type_main.cc", "tpl_spec_return_type.cc", "tpl_spec_return_type.h", "name_trait.h"],
)

cc_binary(
    name = "auto_inference",
    srcs = ["auto_inference.cc", "name_trait.h"],
)
