cc_binary(
    name = "copy_ctor",
    srcs = ["copy_ctor.cc"],
)

cc_binary(
    name = "tpl_inst",
    srcs = ["tpl_inst_main.cc", "tpl_inst.cc", "tpl_inst.h"],
)

cc_binary(
    name = "virtual_template",
    srcs = ["virtual_template.cc"],
)

cc_binary(
    name = "forward",
    srcs = ["forward.cc"],
)

cc_binary(
    name = "recursive_template",
    srcs = ["recursive_template.cc"],
)

cc_binary(
    name = "name_trait",
    srcs = ["name_trait.cc", "name_trait.h"],
)
