method: grid
parameters:
  custom_toggle:
    distribution: categorical
    values: [true]

project: uncategorized
program: ./train_wandb_pl_main.py
command:
- ${program}
- --is_wandb_sweep
- --wandb_sweep_json
- ${args_json}
