package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "voxel_grid",
    srcs = [
        "voxel_grid.cpp",
    ],
    deps = [
        "@eigen",
        "@pcl_io//:lib",
        "@pcl_filters//:lib",
    ],
)
