cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["@eigen//:eigen"],
)

cc_binary(
    name = "coeffwise",
    srcs = ["coeffwise.cc"],
    deps = ["@eigen//:eigen"],
)

cc_binary(
    name = "const_ref_ambiguity",
    srcs = ["const_ref_ambiguity.cc"],
    deps = ["@eigen//:eigen"],
)

cc_binary(
    name = "eigen_bug279_followup",
    srcs = ["eigen_bug279_followup.cc"],
    deps = ["@eigen//:eigen"],
)

cc_binary(
    name = "autodiff_nth_order",
    srcs = ["autodiff_nth_order.cc"],
    deps = ["@eigen//:eigen"],
)

cc_binary(
    name = "autodiff_mod",
    srcs = ["autodiff_mod.cc", "AutoDiffScalarMod.h"],
    deps = ["@eigen//:eigen"],
)
