workspace(name = "my_proj")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

SHA = "dc6e2756130fafb90273587003659cadd1a2dfef3f6464c227794cdc01ebf70e"
VERSION="0.33.0"
http_archive(
    name = "rules_python",
    sha256 = SHA,
    strip_prefix = "rules_python-{}".format(VERSION),
    url = "https://github.com/bazelbuild/rules_python/releases/download/{}/rules_python-{}.tar.gz".format(VERSION,VERSION),
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("//tools/workspace/venv:repository.bzl", "venv_repository")

venv_repository(name = "venv")
