workspace(name = "multibody_plant_prototypes")

# Adapted from:
# https://github.com/RobotLocomotion/drake-external-examples/tree/e86cd4755a8545aee801ad4984dc1d84c8e67fd8

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz",
    sha256 = "aa96a691d3a8177f3215b14b0edc9641787abaaa30363a080165d06ab65e1161",
)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

DRAKE_RELEASE = "20200514"  # v0.18.0
DRAKE_CHECKSUM = "b2d42917bcc7e6ae1f4f1be480b89cc3e91dd4667ab42bea88c53da75ccdaafd"

http_archive(
    name = "drake_artifacts",
    url = "https://drake-packages.csail.mit.edu/drake/nightly/drake-{}-bionic.tar.gz".format(DRAKE_RELEASE),
    sha256 = DRAKE_CHECKSUM,
    strip_prefix = "drake/",
    build_file_content = "#",
)

load("@drake_artifacts//:share/drake/repo.bzl", "drake_repository")

drake_repository(name = "drake")
