# NOTE: This is a temporary file. Do not version control!
py_binary(
    name = "py_shell",
    srcs = ["//tools:py_shell"],
    deps = [
        "//python/bindings/pymodule:type_binding_test",
    ],
    testonly = 1,
)
