#!/bin/bash
set -eu

# Hacky way to launch Bazel with a virtualenv.

workspace_dir=$(cd $(dirname ${BASH_SOURCE})/.. && pwd)
# Ensure that the venv is setup.
${workspace_dir}/setup.sh

# Run bazel.
exec bazel-real "$@"
