files:
- drake/geometry/render/render_engine.h

drake:
  geometry:
    render:
      classes:
        ClippingRange: {}
        RenderCameraCore: {}
        ColorRenderCamera: {}
        DepthRange: {}
        DepthRenderCamera: {}
