files:
- clang/AST/ASTContext.h
- clang/AST/DeclCXX.h
- clang/Frontend/CompilerInstance.h

clang:

  classes:
    CompilerInstance: {}
    ASTContext: {}

    Decl: {}
    NamedDecl: {}
    CXXRecordDecl: {}    
