name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  new:
    name: new
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build and test
      run: ./setup/ci/build_and_test.sh
      shell: bash
